### ISSUE TITLE
Update content documentation

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#531]
We will need to update the content documentation (in the training materials, content process docs, etc) about the following changes, which impact the content workflow:
- #318 Support ordering categories in a separate file
- #405 Create landing page for agencies
- #522 Content with multiple sources

**Comment by brentryanjohnson** [comment]
Adjusted in the [wiki](https://github.com/18F/cv_faq/wiki/Content-management-in-cv_faq). Please review before closing (if you have time), @allisonnorman and @Mtcarp

**Comment by brentryanjohnson** [comment]
FYI @allisonnorman, I didn't add anything about the agency page, since it's autogenerated. If you think we need documentation about the mechanics of that page from a content perspective, I'm happy to add it. :)

**Comment by brentryanjohnson** [comment]
Change log

## Sources
Here's how the front matter in content files works:
- `title`: The title, formatted as a question, that appears in the accordion on the site
- `category`: The category this content belongs to. The format must match the `name` key in the respective category markdown file. For example, the `category` value in the example above must match the `name` value in the `keeping-home-safe.md` file located in the `_categories` directory.
- `layout`: Selects the layout for this content (as a content manager, you'll probably never change this).
- 'date`: The date that will appear as "Last updated" for each question.
- `sources`: Lists the government agency content "owner" and webpage
  - `agency`: Government agency that "owns" the content (`agency` must be preceded by a hyphen `-`)
  - `url`: Government agency webpage with the source content
- `promoted`: If set to `true`, this will move the content up the list of questions in each category. If only one markdown file is set to `true`, it will appear at the top of the list on its category page. If several files are set to true, they will sort alphabetically above those set to `false`. If none are set to `true`, the order will be alphabetical.
- `excerpt`: A field for entering concise descriptions of the content (we don't use this at the time of this writing)

##### Multiple sources

Some content files have two sources. Here's the format when there are two sources:

```
sources:
- agency: treasury
  url: https://home.treasury.gov/news/press-releases/sm953
- agency: irs
  url: https://www.irs.gov/coronavirus
```

## Category order
```
---
layout: category
name: rumors
title: "Rumor control"
owner: FEMA
banner:
  display: false
  heading: "This is a place to place urgent information"
  content: "You can set this component to 'display: true' to show a banner at the top of the page."
---
```
Here's how the front matter in category files works:
- `layout`: Selects the layout for categories (as a content manager, you'll probably never change this).
- `name`: The category name that links category markdown files to content markdown files. The `name` in content markdown files for each category must match what's entered here for that category. The format should be lowercase, with multiple words separated by hyphens (computers appreciate this sort of thing). Here's another example: `parents-and-children`.
- `title`: The title of the category. This is what will show up on the webpage.
- `owner`: A place to enter the "owner" of the content for this category, probably a government agency.
- `banner`: An alert banner that will show up on the category page, styled in yellow with an icon above the main content.
  - `display`: Set to `true` or `false`. The banner will show up on the page when set to `true`.
  - `heading`: Heading text, styled as a heading level 3 (`<h3>`)
  - `content`: This is content of alert that will show up under the alert heading.

### Homepage category order
A separate file in the `_data` directory determines the order of categories on the homepage. In that directory, you can change the order of categories in the homepage layout by adjusting the order in `homepage_order.yml`. The file looks like this:

```
categories:
  - name: symptoms-and-testing
  - name: spread
  - name: travel
  - name: keeping-home-safe
  - name: funerals
  - name: parents-and-children
  - name: pregnancy
  - name: support-for-business
  - name: community-events
  - name: k12-childcare
  - name: water-transmission
  - name: rumors
  - name: protect-yourself
  - name: underlying-conditions
  - name: retirement-communities
  - name: animals
  - name: basics
  - name: financial-help
```
Again, mind indentation in your YAML file. :)

Also, if you add or remove a category, you'll need to add or remove it here. For instance, if you add a category for `sports-venues`, you'll need to add it here, and place it in the order in which you want it to appear on the homepage.
